<?php
/** @var \BlueChili\AjaxCart\Block\Ui\Related $block */

if (($items = $block->getItems()) && $items->count()):
    $title = __('Products you might like!');
?>
<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
<?php 
$size = array(
	'width' => 300,
	'height' => 300,
);
?>
    <div class="block popup__related">
        <div class="block-title title">
            <h5 id="block-related-heading" role="heading" aria-level="2"><?php echo $block->escapeHtml($title); ?></h5>
        </div>
        <div class="block-content content" aria-labelledby="block-related-heading">
            <div class="products wrapper grid products-grid products-related">
                <ol data-related-block="items" class="products list items product-items owl-carousel">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $item): ?>
                        <?php $available = ''; ?>

                        <?php if (!$item->isComposite() && $item->isSaleable()): ?>
                            <?php if (!$item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <li class="item product product-item">
                            <div class="product-item-info <?php  /* @noEscape */ echo $available; ?>">
                                <a href="<?php echo $block->escapeUrl($block->getProductUrl($item)) ?>"
                                   class="product photo product-item-photo">
                                    <?php $productImage = $_imagehelper->init($item, 'product_small_image')->resize($size['width'], $size['height'])->getUrl(); ?>
                                    <img src="<?php echo $productImage; ?>" alt="<?php echo $block->escapeHtml($item->getName()) ?>" class="img-fluid"/>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" title="<?php echo $block->escapeHtml($item->getName()) ?>" href="<?php echo $block->escapeUrl($block->getProductUrl($item)) ?>">
                                            <?php echo $block->escapeHtml($item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($item); ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        require([
            'jquery',
            'mgsowlcarousel'
        ], function ($) {
            $('.popup__related .products.list.product-items').owlCarousel({
                items: 3,
                autoplay: false,
                autoplayHoverPause: true,
                nav: false,
                dots: true,
                responsive:{
                    0:{
                        items:2
                    },
                    576:{
                        items:2
                    },
                    768:{
                        items:3
                    }
                }
            });
        });
    </script>
<?php endif;?>
