<?php
/* @var $block \BlueChili\AjaxCart\Block\Source\Actions */
?>
<script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>

<script type="text/x-magento-init">
{
	"[data-role=tocart-form], .form.map.checkout": {
		"catalogAddToCart": {}
	}
}
</script>